language: php

os:
  - linux

php:
  - 7.0

sudo: false

install:
  - composer install --no-interaction

script:
  - composer test

branches:
  only: master

cache:
  directories:
    - vendor
    - $HOME/.composer/cache