language: php

os:
  - linux

php:
  - 7.4

sudo: false

install:
  - composer install --no-interaction

script:
  - composer test

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only: master

cache:
  directories:
    - vendor
    - $HOME/.composer/cache